name: Equinix Prices
on:
  workflow_dispatch:
  
jobs:
  get-prices:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Terraform Plan
      id: plan
      run: |
        PRICES=$(curl -X GET -H "X-Auth-Token: ${{ secrets.TOKEN }}" $URL -d "metro=$METRO" | \
        python3 -c "import sys, json; print(json.load(sys.stdin)['spot_market_prices']['am'])"| sed "s/'/\"/g")
        echo $PRICES
      continue-on-error: false
      shell: bash
      env:
        URL: "https://api.equinix.com/metal/v1/market/spot/prices/metros"
        METRO: "am"
